### ISSUE TITLE
using an xc potential without the energy functional 

### ISSUE THREAD

**Issue by aouinaayoub** [JuliaMolSim/DftFunctionals.jl#10]
I would like to use a new xc potential in the Kohn-Sham Hamiltonian for a given system. This xc potential does not have an energy functional, it reads: 

 

$v_{\rm xc}({\bf r},[n]) =  v^{\rm LDA}_{\rm xc} (n^c_r )$

where:
$n({\bf r})$ is the electronic density,

$v^{\rm LDA}_{\rm xc}(n)$ is the LDA xc potential function,

$n^c_{\bf r} = \int d {\bf r}' \frac{f_{\rm xc}( |{\bf r}-{\bf r}'|, n_0) }{f^h_{\rm xc}(n'_0)} n({\bf r}')$,

with $f_{\rm xc}(|\mathbf{r}-\mathbf{r}'|,n_0)=\left.\delta v_{\rm xc}(\mathbf{r},[ n])/\delta n(\mathbf{r}')\right|{n=n_0}$ is the static non local xc kernel of the homogeneous electron gas with density $n_0$, and $f^h_{\rm xc}(n'_0)$ is its limit of zero wave-vector. Both functions are parameterized and available,

$n_0=\frac{n({\bf r})+n^c_{\bf r}}{2}$ and $n'_0=\frac{n({\bf r})+n({\bf r'})}{2}$.

Could you provide me with guidelines to implement and use this functional?

**Comment by antoine-levitt** [comment]
So in general if you want a new term that isn't covered by the existing ones you have to implement it yourself: look at hartree.jl for instance. If you don't have an energy functional, you can set it to an arbitrary value; it might break things in DFTK (like the default heuristics for the SCF) but that can be fixed. The issue I see here is that your potential function is not a simple form in the density, because the kernel K(r,r') = fxc(r-r', n0)/fxch(n0') looks like a general nonseparable function of r and r' (not of r-r'). You can implement it directly, but it will probably be pretty expensive. I'd start by getting and idea of how costly (in flops and in ram) it is to form the matrix K(r,r') for all r,r' in the grid (of size basis.fft_size), for the system of interest. If it's doable you can try, but you will very likely be limited to very small systems.

**Comment by aouinaayoub** [comment]
I don't find hartree.jl. I also checked the documentation, I don't see how to implement my own xc potential, could you write a snippet of code how to personalize the vxc let's say for $v_{\rm xc}=\int d{\bf r'} n({\bf r'})/|{\bf r-r'}$| ? (I'm very beginner with julia)

**Comment by antoine-levitt** [comment]
hartree.jl is here: https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/terms/hartree.jl, it does exactly what you say here https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/terms/hartree.jl#L45 and here https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/terms/hartree.jl#L33. Note that this uses the convolution theorem and FFTs (because 1/|r-r'| is a function of r-r'), which is not feasible in your case. You need something like (in real space) `pot = reshape(K * vec(total_density(ρ)), basis.fft_size)` where `K` is a matrix of size `prod(basis.fft_size)` by itself.

**Comment by antoine-levitt** [comment]
You add it as an extra term, see the `extra_terms` keyword argument in the `model_DFT` constructor (in standard_models.jl) and eg this tutorial: https://docs.dftk.org/dev/examples/gross_pitaevskii/. Let us know how that goes!

**Comment by aouinaayoub** [comment]
Thanks a lot!
